export const posts = [
  {
    title: 'Cursed Pirates — Update 11/10/2022',
    href: 'https://blog.galleon.community/cursed-pirates-update-11-10-2022-4e99739dc8fe',
    category: {
      name: 'Galleon',
      href: 'https://blog.galleon.community/cursed-pirates-update-11-10-2022-4e99739dc8fe',
    },
    description: 'A quick round-up of information for ye scurvy dogs around the development of Cursed Pirates & Cursed DAO.',
    date: 'Oct 13',
    datetime: '2022-10-13',
    imageUrl: 'https://miro.medium.com/max/700/1*mEECLeRT3Ofsn4wXY2ESfA.png',
    readingTime: '6 min',
    author: {
      name: 'Davy Jones',
      href: 'https://andrew-eth.medium.com',
      imageUrl: 'https://miro.medium.com/fit/c/176/176/1*FmOvNmeaHZwrkEAIrwbnfw.png',
    },
  },
  {
    title: 'Zero Bloat Get Setup In Crypto',
    href: 'https://andrew-eth.medium.com/zero-bloat-get-setup-in-crypto-1ff462c69431',
    category: {
      name: 'Personal',
      href: 'https://andrew-eth.medium.com/zero-bloat-get-setup-in-crypto-1ff462c69431',
    },
    description: 'Lazy speculator or on-chain maximalist, what are you?',
    date: 'Sep 26',
    datetime: '2022-09-26',
    imageUrl: 'https://miro.medium.com/max/700/1*hWh2unZzs1pNb-_S7CyIFg.png',
    readingTime: '10 min',
    author: {
      name: 'Andrew',
      href: 'https://andrew-eth.medium.com',
      imageUrl: 'https://miro.medium.com/fit/c/176/176/1*hWh2unZzs1pNb-_S7CyIFg.png',
    },
  },
  {
    title: 'Introducing Cursed DAO, a Galleon NFT Focused Sub DAO',
    href: 'https://blog.galleon.community/introducing-cursed-dao-a-galleon-nft-focused-sub-dao-ac85fbf66025',
    category: {
      name: 'Galleon',
      href: 'https://blog.galleon.community/introducing-cursed-dao-a-galleon-nft-focused-sub-dao-ac85fbf66025',
    },
    description: 'And are you prepared for what comes after? The cursed are not bound to me. They are bound to a lifetime of servitude before the mast.',
    date: 'Aug 31',
    datetime: '2022-08-31',
    imageUrl: 'https://miro.medium.com/max/700/1*rpHFmA8ZzV_QdtaSdDcBxw.png',
    readingTime: '7 min',
    author: {
      name: 'Davy Jones',
      href: 'https://andrew-eth.medium.com',
      imageUrl: 'https://miro.medium.com/fit/c/176/176/1*FmOvNmeaHZwrkEAIrwbnfw.png',
    },
  },
  {
    title: 'Captain’s Log #2 — Outlook & Strategic Shift',
    href: 'https://blog.galleon.community/captains-log-2-outlook-strategic-shift-26e2d092c0d7',
    category: {
      name: 'Galleon',
      href: 'https://blog.galleon.community/captains-log-2-outlook-strategic-shift-26e2d092c0d7',
    },
    description: 'Day 206 at sea. Galleon came afoot into an unchartered, parched archipelago where the dominant land, sea and air mammal were bears.',
    date: 'Aug 26',
    datetime: '2022-08-26',
    imageUrl: 'https://miro.medium.com/max/700/1*LJ59F8yShJBUwT7x19WSNQ.png',
    readingTime: '8 min',
    author: {
      name: 'Davy Jones',
      href: 'https://andrew-eth.medium.com',
      imageUrl: 'https://miro.medium.com/fit/c/176/176/1*FmOvNmeaHZwrkEAIrwbnfw.png',
    },
  },
  {
    title: 'Below Deck — Black Flag Coalition Faction Preview',
    href: 'https://blog.galleon.community/below-deck-black-flag-coalition-faction-preview-1e207a7f8f10',
    category: {
      name: 'Cursed Pirates',
      href: 'https://blog.galleon.community/below-deck-black-flag-coalition-faction-preview-1e207a7f8f10',
    },
    description: 'Today we’re excited to share a preview of the Cursed Pirates latest faction with you, the Black Flag Coalition.',
    date: 'Aug 11',
    datetime: '2022-08-22',
    imageUrl: 'https://miro.medium.com/max/700/0*p5JDsY_wzp7afPuk.png',
    readingTime: '4 min',
    author: {
      name: 'Davy Jones',
      href: 'https://andrew-eth.medium.com',
      imageUrl: 'https://miro.medium.com/fit/c/176/176/1*FmOvNmeaHZwrkEAIrwbnfw.png',
    },
  },
  {
    title: 'Captain’s Log #1 — Galleon Recap, Port to Voyage',
    href: 'https://blog.galleon.community/captains-log-1-galleon-recap-port-to-voyage-ec1a812b64df',
    category: {
      name: 'Galleon',
      href: 'https://blog.galleon.community/captains-log-1-galleon-recap-port-to-voyage-ec1a812b64df',
    },
    description: 'A holistic view of the progress Galleon has made in its initiatives dating back to its Seed raise.',
    date: 'Jun 06',
    datetime: '2022-06-06',
    imageUrl: 'https://miro.medium.com/max/700/1*Ffq7OZIZmmYOeL5JUSk50A.png',
    readingTime: '8 min',
    author: {
      name: 'Davy Jones',
      href: 'https://andrew-eth.medium.com',
      imageUrl: 'https://miro.medium.com/fit/c/176/176/1*FmOvNmeaHZwrkEAIrwbnfw.png',
    },
  },
];
